services:
  postgres-url-db:
    image: "postgres:latest"
    container_name: postgres-url-db
    expose:
      - "5434"
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: betmart
      POSTGRES_PASSWORD: betmart
      PGPORT: 5434
    volumes:
      - postgres-url-db:/var/lib/postgresql/url/data
  url:
    build:
      context: .
    container_name: shortener
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: betmart
      POSTGRES_PASSWORD: betmart
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-url-db:5434/url
      SPRING_DATASOURCE_USERNAME: betmart
      SPRING_DATASOURCE_PASSWORD: betmart
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-url-db
volumes:
  postgres-url-db:
    driver: local